### ISSUE TITLE
errors trying to install into posrtgresql 9.4.0 

### ISSUE THREAD

**Issue by jhuijsing** [dimitri/prefix#12]
downloaded an compiled ok

the make install 
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./prefix--1.2.0.sql '/usr/share/pgsql/contrib'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./prefix--unpackaged--1.2.0.sql '/usr/share/pgsql/contrib'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./prefix--1.1--1.2.0.sql '/usr/share/pgsql/contrib'
 /bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 755  prefix.so '/usr/lib64/pgsql'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./README.md '/usr/share/doc/pgsql/contrib'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./TESTS.md '/usr/share/doc/pgsql/contrib
puts the file in  /usr/share/pgsql/contrib'

then tried
psql <connection string> -c 'CREATE EXTENSION prefix;'
this failed 

A bit of googlng  later i put the file in  /usr/local/pgsql/share/extension
now it fails with 
ERROR:  could not access file "$libdir/prefix": No such file or directory

ANy hints to what is going wrong
# pg_config --pkglibdir

/usr/lib64/pgsql

**Comment by ChristophBerg** [comment]
Re: jhuijsing 2015-06-01 <dimitri/prefix/issues/12@github.com>
>  /bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 755  prefix.so '/usr/lib64/pgsql'
> puts the file in  /usr/share/pgsql/contrib'
> A bit of googlng  later i put the file in  /usr/local/pgsql/share/extension
> now it fails with 
> ERROR:  could not access file "$libdir/prefix": No such file or directory
> # pg_config --pkglibdir
> /usr/lib64/pgsql

Prefix .so is put into the directory reported by --pkglibdir.

It looks like your pg_config doesn't match your running PostgreSQL
server. Do you have several installations on disk?

Try passing PG_CONFIG=/usr/local/pgsql/bin/pg_config to the make
invocations.

Christoph
-- 
cb@df7cb.de | http://www.df7cb.de/
