### ISSUE TITLE
cast(prefix_range as text) as implicit

### ISSUE THREAD

**Issue by infofarmer** [dimitri/prefix#14]
There are is a cast to/from text, but only one of them is implicit. We're using text and prefix_range interchangeably in our DB and it would be convenient to have the second cast implicit as well. Any specific reason for why it is not?

CREATE CAST (text as prefix_range) WITH FUNCTION prefix_range(text) AS IMPLICIT;
CREATE CAST (prefix_range as text) WITH FUNCTION text(prefix_range);

**Comment by dimitri** [comment]
Yes, to avoid forcing PostgreSQL hand into working with prefix_range operators in cases where it's obvious that you mean a text operator. Obvious doesn't translate that well into PostgreSQL operator choices, but it is spelled `implicit` anyway...

**Comment by infofarmer** [comment]
Isn't there precedence to handle this? Also, an uneducated guess would be that it is the first cast being implicit that would make prefix_range ops available for text, not the second one.

**Comment by dimitri** [comment]
It is always safe to use a `prefix_range` as a text in a context where you don't have a specific operator, hence the first implicit cast. In the second case it would allow any text to be considered as a prefix range, and I didn't want that to happen by default. Of course feel free to try and change the CAST to see what happens, it might be what you want here...

**Comment by infofarmer** [comment]
I did, by updating pg_catalog.

Still, I'm not quite getting this. You have prefix_range(text) as implicit — converting any text to prefix_range, so that any text can be considered as a prefix_range.

What you don't have as implicit is text(prefix_range) — something that would allow using text ops on prefix_range.

I think you're trying to avoid the current status quo, or I just don't understand something. An example would be much appreciated. Thanks!

**Comment by dimitri** [comment]
Will get back to you on that (getting very late here), keeping open so that I can remember about the case.
