### ISSUE TITLE
strange length calculation

### ISSUE THREAD

**Issue by dmitry-sinina** [dimitri/prefix#15]
I tried using prefixes in range notation(with brackets) but I am a bit confused because length() works incorrectly in this case

```
yeti=# SELECT *, length(prefix) from (values('12345'::prefix_range), ('123[3-4]'::prefix_range)) as data(prefix)  where prefix@>'123456789' order by length(prefix);
  prefix  | length 
----------+--------
 12345    |      5
 123[3-4] |      5
```

Using this query I can't find best prefix for number 123456789, because length comparison does not work. I think length('123[3-4]'::prefix_range) must return 4 instead of 5

**Comment by dimitri** [comment]
You're right about `123[3-4]` having a length of 4 digits. Are you in a position to provide a patch to fix that bug? Thanks!

**Comment by dmitry-sinina** [comment]
Seems I have to fix expected/queries.out.  Looks like it contains wrong test results:
```
select length('123[4-5]'::prefix_range);
 length 
--------
      5
(1 row)
```

**Comment by dimitri** [comment]
Thanks for the fix, I merged it!
